// <auto-generated />
namespace FotoShoutApi.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SeperateFirstnLastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeperateFirstnLastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201307102304493_SeperateFirstnLastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
